import { NextRequest, NextResponse } from 'next/server'
import { analyzeMatch } from '@/lib/skill-matcher'

export async function POST(request: NextRequest) {
  try {
    const { jobDescription, resumeText, isUrl } = await request.json()
    
    if (!jobDescription || !resumeText) {
      return NextResponse.json(
        { error: 'Job description and resume text are required' },
        { status: 400 }
      )
    }
    
    // Perform client-side analysis
    const results = analyzeMatch(jobDescription, resumeText)
    
    return NextResponse.json({
      ...results,
      sankey_image: null, // Will be generated by Lambda when deployed
      radar_image: null   // Will be generated by Lambda when deployed
    })
  } catch (error) {
    console.error('Analysis error:', error)
    return NextResponse.json(
      { error: 'Failed to analyze match' },
      { status: 500 }
    )
  }
}
